CREATE TABLE users (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	  firstName VARCHAR(20) NOT NULL,
	  lastname VARCHAR(50) NOT NULL,
	  password VARCHAR(255) NOT NULL,
	  createdAt DATE DEFAULT NOW()
) ENGINE = InnoDB;

CREATE TABLE notes (
	  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	  title VARCHAR(255) NOT NULL,
	  userId INT(11) UNSIGNED NOT NULL,
	  message VARCHAR(255) NOT NULL,
	   createdAt DATE DEFAULT NOW(),
	  CONSTRAINT `userID`
	    FOREIGN KEY (userId) REFERENCES users (id)
	    ON DELETE CASCADE
	    ON UPDATE RESTRICT
) ENGINE = InnoDB;
